# Test agent

In [1]:
import numpy as np
from numpy.random import default_rng

from chess import Board, Move
from IPython.display import Image, display
from stable_baselines3.common.env_checker import check_env

import sys

sys.path.append('../src')

from games.chess import KRK
from agents.utils import ChessEncoder
from agents.random_agent import RandomAgent
from agents.random_policy import GameUniformPolicy
from games.game_utils import GymEnvFromGameAndPlayer2

In [2]:
env = KRK()
state = env.initial_state
encoder = ChessEncoder()
tablero = encoder.encode_obs(state)
tablero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
action = Move.from_uci('c3c8')
coded_action = encoder.encode_action(state, action)
print(coded_action.shape)
coded_action

action=Move.from_uci('c3c8')
coded_index=18
coded_index=58
(44,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [4]:
idx = 37
encoder.decode_action(state, idx)

casilla_hasta_=(array([4]), array([2]))
c4


Move.from_uci('c3c4')

### Initialize game and other agent

In [5]:
seed = 4
rng = default_rng(seed)

In [6]:
game = KRK(start_position=1)
random_policy = GameUniformPolicy(
    game=game,
    rng=rng,
    encoder=encoder
)

In [7]:
policy_in_state = random_policy.predict(state)
print(policy_in_state.shape)
policy_in_state

(44,)


array([0.02272727, 0.02272727, 0.02272727, 0.02272727, 0.02272727,
       0.02272727, 0.02272727, 0.02272727, 0.02272727, 0.02272727,
       0.02272727, 0.02272727, 0.02272727, 0.02272727, 0.02272727,
       0.02272727, 0.02272727, 0.02272727, 0.02272727, 0.02272727,
       0.02272727, 0.02272727, 0.02272727, 0.02272727, 0.02272727,
       0.02272727, 0.02272727, 0.02272727, 0.02272727, 0.02272727,
       0.02272727, 0.02272727, 0.02272727, 0.02272727, 0.02272727,
       0.02272727, 0.02272727, 0.02272727, 0.02272727, 0.02272727,
       0.02272727, 0.02272727, 0.02272727, 0.02272727])

In [8]:
pl2 = RandomAgent(
    policy=random_policy,
    action_encoder=encoder,
    rng=rng
)

In [9]:
env = GymEnvFromGameAndPlayer2(
    game=game,
    other_player=pl2,
    encoder=ChessEncoder()
)

In [10]:
env.action_space.sample()

np.int64(6)

In [11]:
state = env.reset()
result = env.step(env.action_space.sample())
env.render()

casilla_hasta_=(array([9]), array([2]))


AssertionError: 

In [ ]:
check_env(env)